package model.BC.EO;

import java.math.BigDecimal;

import java.security.SecureRandom;

import java.security.spec.KeySpec;

import javax.crypto.SecretKeyFactory;
import javax.crypto.spec.PBEKeySpec;

import oracle.igf.ids.util.Base64;

import oracle.jbo.AttributeList;
import oracle.jbo.JboException;
import oracle.jbo.Key;
import oracle.jbo.server.DBTransaction;
import oracle.jbo.server.DBTransactionImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.SequenceImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Jan 20 19:07:55 IST 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CUserImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        UserId,
        UserName,
        UserPassword,
        USalt;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int USERID = AttributesEnum.UserId.index();
    public static final int USERNAME = AttributesEnum.UserName.index();
    public static final int USERPASSWORD = AttributesEnum.UserPassword.index();
    public static final int USALT = AttributesEnum.USalt.index();

    /**
     * This is the default constructor (do not remove).
     */
    public CUserImpl() {
    }

    /**
     * Gets the attribute value for UserId, using the alias name UserId.
     * @return the value of UserId
     */
    public BigDecimal getUserId() {
        return (BigDecimal) getAttributeInternal(USERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for UserId.
     * @param value value to set the UserId
     */
    public void setUserId(BigDecimal value) {
        setAttributeInternal(USERID, value);
    }

    /**
     * Gets the attribute value for UserName, using the alias name UserName.
     * @return the value of UserName
     */
    public String getUserName() {
        return (String) getAttributeInternal(USERNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for UserName.
     * @param value value to set the UserName
     */
    public void setUserName(String value) {
        setAttributeInternal(USERNAME, value);
    }

    /**
     * Gets the attribute value for UserPassword, using the alias name UserPassword.
     * @return the value of UserPassword
     */
    public String getUserPassword() {
        return (String) getAttributeInternal(USERPASSWORD);
    }

    /**
     * Sets <code>value</code> as the attribute value for UserPassword.
     * @param value value to set the UserPassword
     */
    public void setUserPassword(String value) {
        setAttributeInternal(USERPASSWORD, value);
    }

    /**
     * Gets the attribute value for USalt, using the alias name USalt.
     * @return the value of USalt
     */
    public String getUSalt() {
        return (String) getAttributeInternal(USALT);
    }

    /**
     * Sets <code>value</code> as the attribute value for USalt.
     * @param value value to set the USalt
     */
    public void setUSalt(String value) {
        setAttributeInternal(USALT, value);
    }

    /**
     * @param userId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(BigDecimal userId) {
        return new Key(new Object[] { userId });
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("model.BC.EO.CUser");
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
    }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        //getting the userid for the customer based on the sequence
        if (operation == DML_INSERT){
            SequenceImpl s = new SequenceImpl("C_USER_SEQ", getDBTransaction());
            BigDecimal cuser_seq = new BigDecimal(s.getSequenceNumber().toString());
            setUserId(cuser_seq);
            }
        //generating the hash value and salt value
        if (operation == DML_INSERT){
            try{
            String salt = getNewSalt();
            String encryptedPassword = getEncryptedPassword(getUserPassword(), salt);
            setUserPassword(encryptedPassword);
            setUSalt(salt);
            }
            catch(Exception ex){
                throw new JboException(ex);
                }

            }
        super.doDML(operation, e);
    }
    
    private String getNewSalt() throws Exception{
            SecureRandom random = SecureRandom.getInstance("");
            byte[] salt = new byte[8];
            random.nextBytes(salt);
            return Base64.encode(salt);
        }

    private String getEncryptedPassword(String password, String salt) throws Exception {
            String algorithm = "";
            int derivedKeyLength = 160; // for SHA1
            int iterations = 20000; // NIST specifies 10000
            byte[] saltBytes = Base64.decode(salt);
            KeySpec spec = new PBEKeySpec(password.toCharArray(), saltBytes, iterations, derivedKeyLength);
            SecretKeyFactory f = SecretKeyFactory.getInstance(algorithm);
            byte[] encBytes = f.generateSecret(spec).getEncoded();
            return Base64.encode(encBytes);
        }

}

